services:
  webserv:
    build: .
    container_name: webserv
    
    platform: linux/amd64

    volumes:
      - ./:/home/student/project
    
    ports:
      - "8080:8080"
      - "8000-8010:8000-8010"

    tty: true
    stdin_open: true
    
    command: tail -f /dev/null